### ISSUE TITLE
how to generates the json file for training?

### ISSUE THREAD

**Issue by SeekPoint** [clarkkev/deep-coref#3]
java -Xmx2g -cp stanford-corenlp.jar:stanford-corenlp-models-3.7.0.jar:* edu.stanford.nlp.coref.NeuralCorefDataExporter <properties-file> <output-path>

what is the edu.stanford.nlp.coref.NeuralCorefDataExporter ?
should I just download the below link?
https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/coref/neural/NeuralCorefDataExporter.java

**Comment by clarkkev** [comment]
As the README says, NeuralCorefDataExporter is part of Stanford CoreNLP. You can download it [here](http://nlp.stanford.edu/software/stanford-corenlp-2017-04-14-build.jar).
